config/routes.rb
ActionController::Routing::Routes.draw do |map|
  
  map.root :controller => :public_front_pages, :action => :show
  map.public_front_page '/', :controller => :public_front_pages, :action => :show

  map.public_article '/articles/:id', :controller => :public_articles, :action => :show
  map.public_page '/pages/*id', :controller => :public_pages, :action => :show
  map.public_category '/categories/*id', :controller => :public_categories, :action => :show
  map.public_search '/search', :controller => :public_search, :action => :show
  map.public_issues '/issues', :controller => :public_issues, :action => :index
  map.public_issue '/issues/:id', :controller => :public_issues, :action => :show
  map.public_blogs '/blogs', :controller => :public_blogs, :action => :index
  map.public_blog '/blogs/:id', :controller => :public_blogs, :action => :show
  map.public_blog_entry '/blogs/:blog_slug/:id', :controller => :public_entries, :action => :show
  map.public_comments '/comments', :controller => :public_comments, :action => :create, :conditions => { :method => :post }
  
  map.feed '/rss', :controller => :public_feeds, :action => :show
  map.feed '/feed.xml', :controller => :public_feeds, :action => :show

  map.front_page_preview '/front_page/preview', :controller => :public_front_pages, :action => :preview 
  
  # Admin routes
  map.admin '/admin', :controller => :dashboards, :action => :dashboard_redirect
  map.with_options(:path_prefix => "/admin") do |admin|
    admin.resources :password_resets
    admin.resources :account_invitations, :only => [:create, :edit, :update, :destroy]
    admin.resources :accounts
    admin.resources :articles, :collection => { :search => :get, :edit_multiple => :get, :update_multiple => :put }, :member => { :lock_comments => :put, :enable_comments => :put, :disable_comments => :put } do |article|
      article.comments '/comments', :controller => :articles, :action => :comments, :conditions => { :method => :get }
      article.resources :mediafiles
      article.resources :authors
      article.resources :tags
      article.resources :waxings
      article.resources :printings
    end
    admin.resources :authors
    admin.resources :blogs, :member => { :manage_contributors => :get, :add_contributor => :put, :remove_contributor => :put, :promote_contributor => :put, :demote_contributor => :put } do |blog|
      blog.resources :entries, :member => { :lock_comments => :put, :enable_comments => :put, :disable_comments => :put } do |entry|
        entry.comments '/comments', :controller => :entries, :action => :comments, :conditions => { :method => :get }
        entry.resources :mediafiles
        entry.resources :waxings
        entry.resources :tags
      end
    end
    admin.resources :categories, :member => { :deactivate => :put, :reactivate => :put }
    admin.resources :comments, :collection => { :search => :get }
    admin.current_design '/current_design', :controller => :designs, :action => :current_design
    admin.resource :dashboard
    admin.resources :designs do |design|
      design.resources :templates
      design.resources :template_files
    end
    admin.resources :documents do |document|
      document.resources :mediafiles
      document.resources :waxings
    end
    admin.resources :entries, :only => [:new, :edit, :update, :destroy], :collection => { :edit_multiple => :get, :update_multiple => :put } do |entry|
      entry.resources :mediafiles
      entry.resources :waxings
      entry.resources :tags
    end
    admin.resource :front_page, :only => [:edit, :update]
    admin.resources :issues, :member => { :upload_pdf => :post } 
    admin.resources :lists, :except => :show 
    admin.resources :mediafiles do |mediafile|
      mediafile.resources :authors
      mediafile.resources :tags
    end
    admin.resource :network, :member => { :checkout_article => :post, :search => :get } do |network|
      network.show_article '/articles/:id', :controller => :networks, :action => :show_article, :conditions => { :method => :get }
      network.show_members '/members', :controller => :networks, :action => :show_members, :conditions => { :method => :get }
      network.update_members '/members', :controller => :networks, :action => :update_members, :conditions => { :method => :post }
    end
    admin.resources :pages
    admin.resources :user_invitations, :only => [:create, :edit, :update, :destroy]
    admin.resources :users, :member => { :promote => :put, :demote => :put, :deputize => :put, :letgo => :delete }
    admin.resources :waxings
  end 
   
end

app/models/account.rb
class Account < ActiveRecord::Base
  include Pacecar
  
  # Main data models (and STI subclasses)
  has_many :mediafiles, :dependent => :destroy
  has_many :images
  has_many :audiofiles
  has_many :documents, :dependent => :destroy
  has_many :articles 
  has_many :entries
  has_many :authors, :dependent => :destroy
  has_many :categories, :order => "position", :conditions => { :active => true }, :dependent => :destroy
  has_many :sections, :order => "parent_id, position", :dependent => :destroy
  has_many :blogs, :dependent => :destroy
  has_many :issues, :dependent => :destroy, :order => "date desc"
  has_many :email_templates, :dependent => :destroy
  has_many :lists, :dependent => :destroy
  has_many :pages, :dependent => :destroy
  has_many :comments, :dependent  => :destroy
  has_many :user_invitations, :dependent => :destroy
  has_many :active_user_invitations, :class_name => 'UserInvitation', :conditions => { :redeemed => false }
  
  has_recent_records :articles
  named_scope :by_most_recently_published,lambda { {:joins => 'INNER JOIN documents ON documents.account_id=accounts.id', :group => 'accounts.id', :order => 'documents.updated_at', :conditions => ["documents.status = 'Published' AND documents.published_at <= ?", Time.now.utc]} }
  
  # Authentication
  has_many :users, :dependent => :destroy
  
  # Join models
  has_many :authorships, :dependent => :destroy
  has_many :photocredits, :dependent => :destroy
  has_many :printings, :dependent => :destroy
  has_many :sortings, :dependent => :destroy
  has_many :waxings, :dependent => :destroy
  
  # Special category functionality 
  has_many :main_categories, :class_name => "Category", :order => "position", :conditions => {:parent_id => nil } # An account's top-level categories
  accepts_nested_attributes_for :categories
  
  acts_as_authorizable
  acts_as_tagger

  validates_presence_of :time_zone, :message => "must indicate preferred time zone."
  
  validates_presence_of :name, :message => "Account must have a name"
  validates_uniqueness_of :name, :message => "Account name must be unique"
  validates_format_of :name, :with => /^[-a-z0-9]+$/
  
  serialize :settings
  serialize :lead_article_ids
  
  has_many  :designs
  belongs_to :current_design, :class_name => "Design", :foreign_key => :current_design_id
  
  # Settings defaults
  IMAGE_DEFAULT_SETTINGS = { 
            "thumb" => ['100>', 'jpg'],  
            "small" => ['250>', 'jpg'],
            "medium" => ['440>', 'jpg'],
            "large" => ['800>', 'jpg']
  }
  
  before_create :set_default_settings
    
  def settings
    read_attribute(:settings)
  end
  
  def display_name
    formal_name || name
  end
  
  FeedSettings = Struct.new("FeedSettings", :limit, :full_text)
  
  def feed_settings
    feed_settings = read_attribute(:settings)["feed"] || {}
    full_text = feed_settings["full_text"]=="true" ? true : false
    FeedSettings.new(feed_settings["limit"].to_i, full_text)
  end
  
  def feed_settings=(new_settings)
    account_settings = read_attribute(:settings)
    account_settings["feed"] = {} if settings["feed"].nil?
    account_settings["feed"].merge!(new_settings)
    write_attribute(:settings, account_settings)
  end
  
  def image_settings
    account_settings = read_attribute(:settings)
    account_settings["image"].nil? ? {} : account_settings["image"]
  end
  
  def image_settings=(new_settings)
    account_settings = read_attribute(:settings)
    account_settings["image"] = {} if settings["image"].nil?
    raise ArgumentError unless new_settings.is_a? Hash
    new_settings.each do |key, value|
      
      if value[:height].blank?
        new_height = ""
      else
        new_height="x" + value[:height]
      end
      
      if value[:width].blank?
        new_width = ""
      else
        new_width= value[:width]
      end
      
      account_settings["image"].update( key => [new_width + new_height + ">", "jpg"]) unless new_height.blank?&&new_width.blank?
    end
    write_attribute(:settings, account_settings)
  end
  
  # Human readable list of account managers
  def managers_list
    managers = self.has_managers
     case managers.length
     when 0
       return nil
     when 1
       return "#{managers.first.name} <#{managers.first.email}>"
     when 2
       return "#{managers.first.name} <#{managers.first.email}>" + " and " + "#{managers.second.name} <#{managers.second.email}>"
     else
      list = String.new
      (0..(managers.length - 3)).each{ |i| list += "#{managers[i].name} <#{managers[i].email}>, " }
      list += "#{managers[managers.length-2].name} <#{managers[managers.length-2].email}>" + " and " + "#{managers[managers.length-1].name} <#{managers[managers.length-1].email}>" # last two managers get special formatting
      return list
    end         
  end

  def to_xml(options = {})
     options[:indent] ||= 2
     xml = options[:builder] ||= Builder::XmlMarkup.new(:indent => options[:indent])
     xml.instruct! unless options[:skip_instruct]
     
     xml.account do
       xml.tag!( :id, self.id )       
       xml.tag!( :name, self.name)
       xml.tag!( :time_zone, self.time_zone)
     end
  end
  
  # Account user management
  def promote(user)
    if user.has_role?('staff', self)
      if user.has_role?('editor', self)
          user.has_no_role('editor', self)
          user.has_role('manager', self)
      else
        user.has_role('editor', self)
      end
    else
      user.has_role('staff', self)
    end
  end
  
  def demote(user)
    if user.has_role?('manager', self)
      user.has_no_role('manager', self)
      user.has_role('editor', self)
    elsif user.has_role?('editor', self)
      user.has_no_role('editor', self)
    elsif user.has_role?('staff', self)
      user.has_no_role('staff', self)
    end
  end
    
  # Network
  has_many :checkouts, :dependent => :destroy
  has_many :network_memberships, :class_name => "Membership", :foreign_key => :network_owner_id, :dependent => :destroy
  has_many :network_members, :through => :network_memberships, :source => :account
    
  def network_owner?
    !network_memberships.reload.empty?
  end
  
  def has_network_member?(potential_member)
    !!network_memberships.find_by_account_id(potential_member.id)
  end
  
  def network_member_ids
    network_memberships.collect{ |m| m.account_id }
  end
      
  def make_network_copy(article, user = nil)
    if has_network_member?(article.account)&&article.published?
      copy = article.clone
      copy.unpublish
      copy.update_attributes(:account => self, :section => nil)
    
      article.authors.each do |author|
        copy.authors << authors.find_or_create_by_name(author.name)
      end
      copy.tag_list = article.tag_list
      article.mediafiles.each do |m| 
        mediafile_copy = m.photocopy(self)
        copy.mediafiles << mediafile_copy 
        copy.waxing_for(mediafile_copy).update_attribute(:caption, article.waxing_for(m).caption)
      end
      checkouts.create(:original_article => article, :duplicate_article => copy, :user => user )
      copy
    end
  end  
  
  def has_network_copy_of?(article)
    !!find_network_copy_of(article)
  end
  
  def find_network_copy_of(article)
    checkout = checkouts.find_by_original_article_id(article.id)
    checkout.nil? ? nil : checkout.duplicate_article
  end
  
  def site_url
    read_attribute("site_url") || ""
  end
  
  private
  
  def set_default_settings
    write_attribute(:settings, { "image" => IMAGE_DEFAULT_SETTINGS } )
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :account
  
  has_many :printings, :dependent => :destroy
  has_many :articles, :through => :printings

  named_scope :processed, :conditions => { :processing => false }

  has_attached_file :pdf,
      :styles => {
        :screen_quality => { :quality=>'screen', :processors => [:pdf_quality_filter]},
        :system_cover_thumb => ["175>", 'jpg'],
        :system_default => ["400>", 'jpg']
      },
      :convert_options => {
        :all => "-colorspace RGB"
      },
      :default_url => '/images/no_issue_cover_small.jpg',
      :default_style => :system_cover_thumb,
      :path => ":rails_root/public/system/:account/:class/:id_partition/:basename_:style.:extension",
      :url => "/system/:account/:class/:id_partition/:basename_:style.:extension"
  
  
  validates_presence_of :account
  validates_associated :account, :message => "must be valid"
  validates_date :date, :format => "yyyy-mm-dd", :invalid_date_message => "must be formattted 'YYYY-MM-DD' style"
  
  # Default settings
  # Right now these image sizes are processed automatically.
  def settings
       default_settings = {
        "thumb" => ['50>', 'jpg'],
        "small" => ['148>', 'jpg'],
        "medium" => ['500>', 'jpg'],
        "large" => ['800>', 'jpg']
        }
    if self.account
      default_settings.merge!(self.account.settings["issue"]) if self.account.settings["issue"] if self.account.settings
      return default_settings
    else
      return default_settings 
    end
  end
  
  # Callbacks
  before_pdf_post_process do |issue|
    issue.processing = true if issue.pdf.dirty? # If the PDF has changed, mark the issue for processing
    
    false if issue.processing? # do not process if just added, processing attribute defaults to 'true'
  end
  
  after_update do |issue|
    Delayed::Job.enqueue IssueJob.new(issue.id) if issue.processing? # add to queue if the PDF is new
  end
  
  # DelayedJob for PDF processing
  def perform
    self.processing = false # unlock for processing
    pdf.reprocess! # do the processing
    save
  end
  
  # Fix the mime types on uploaded PDFs. Make sure to require the mime-types gem
  def swfupload_file=(data)
    data.content_type = MIME::Types.type_for(data.original_filename).to_s
    self.pdf = data
  end
  
  def pdf_url(style = :original)
    if self.pdf && processing? && style != :original
      return pdf.send(:interpolate, '/images/processing_issue.jpg', "#{style}")
    end
    pdf.url(style)
  end
  
  def to_xml(options = {})
      options[:indent] ||= 2
      xml = options[:builder] ||= Builder::XmlMarkup.new(:indent => options[:indent])
      xml.instruct! unless options[:skip_instruct]
      
      xml.issue do 
        xml.tag!( :id, self.id )
        xml.tag!( :account_id, self.account.id )
        xml.tag!( :account_name, self.account.formal_name.blank? ? self.account.name.capitalize : self.account.formal_name )

        xml.tag!( :date, self.date )
        xml.tag!( :name, self.name )
        xml.tag!( :description, self.description )
        xml.tag!( :volume, self.volume )
        xml.tag!( :number, self.number )

        xml.tag!( :press_pdf_file, self.pdf.url(:original) )
        if self.pdf.path(:screen_quality) && File.exists?(self.pdf.path(:screen_quality))
          xml.tag!( :screen_pdf_file, self.pdf.url(:screen_quality) )
        else
          xml.tag!( :screen_pdf_file, self.pdf.url(:original) )
        end
        xml.tag!( :large_cover_image, self.pdf.url(:system_default) )
        xml.tag!( :small_cover_image, self.pdf.url(:system_cover_thumb) )

        xml.tag!(:created_at, self.created_at.to_formatted_s(:long))
        xml.tag!(:last_updated, self.updated_at.to_formatted_s(:long))
      end
  end
  
end

app/views/articles/_article.html.erb
<li <% if article.draft?%>class="draft"<% elsif article.scheduled? %>class="scheduled"<% elsif article.awaiting_attention? %>class="awaiting_attention"<% end %>>
	<div class="clearfix">
		<div class="select">
			<input type="checkbox" value="<%= article.id %>" name="article_ids[]"/>
		</div>
	
		<div class="details">
			<h1>&ldquo;<%= link_to article.title, document_url_for_user(article, current_user)  %>&rdquo; <small><%= publication_status_for(article) %></small></h1>
			<div class="mediafiles">
				<% if mediafile = article.mediafiles.first %>				
					<% if mediafile.is_a?(Image) %>
						<a class="image_icon first large" href="<%= mediafile.file.url(:large) %>"><%= image_tag(mediafile.file.url(:thumb)) %></a>
						<a class="image_icon first small" href="<%= mediafile.file.url(:large) %>"><%= image_tag(mediafile.file.url(:system_icon)) %></a>
					<% elsif mediafile.is_a?(Audiofile) %>
						<object type="application/x-shockwave-flash" data="/player_mp3.swf" width="27" height="22">
		                    <param name="movie" value="/player_mp3.swf" />
		                    <param name="FlashVars" value="mp3=<%= mediafile.file.url %>&amp;showslider=0&amp;width=27&height=22" />
		                </object>    
					<% end %>
				<% end %>
				<% if article.mediafiles.count > 1 %>
					<% article.mediafiles[1..-1].each do |mediafile| %>
						<% if mediafile.is_a?(Image) %>
							<a class="image_icon" href="<%= mediafile.file.url(:large) %>"><%= image_tag(mediafile.file.url(:system_icon), :alt => article.caption_for(mediafile) ) %></a>
						<% elsif mediafile.is_a?(Audiofile) %>
							<object type="application/x-shockwave-flash" data="/player_mp3.swf" width="27" height="22">
			                    <param name="movie" value="/player_mp3.swf" />
			                    <param name="FlashVars" value="mp3=<%= mediafile.file.url %>&amp;showslider=0&amp;width=27&height=22" />
			                </object>    
						<% end %>
					<% end %>
				<% end %>
			</div>
			<% if article.network_article? %>
			<p style="float: right;"><small>Originally published by <strong><%= article.checkout.original_account.display_name %></strong></small></p>
			<% end %>
			<p><%= article.authors_list %></p>
		</div>
	
		<div class="section">
			<p> <%= article.section.blank? ? "<span style=\"color: #BBB\">No section</span>" : article.section.name %></p>
		</div>

		<div class="tags_comments">
			<div class="tags">
				<% unless article.tag_list.blank? %>
					<p><em> <%= article.tag_list %></em></p>
				<% else %>
					<p><em><span style="color: #BBB">No tags</span> </em></p>
				<% end %>
			</div>
		
			<div class="comments">
				<%unless article.comments.empty?%><p><%= pluralize(article.comments.count, "comment") %></p><%end%>
			</div>
		</div>
		
		<div class="date">
			<p><%= h article.date.to_s(:standard) %></p>
			<p class="word_count"><%= pluralize(article.word_count, "word") %></p>
		</div>
		<%= link_to "X", article, :confirm => "You are about to delete the article: \n \n &quot;" + h(article.title) + "&quot;\n \n Click 'OK' to delete or 'Cancel' to return to the page.", :method => :delete, :class=>"destroy_link" %>
	</div>
</li>

app/views/articles/edit.html.erb
<% content_for :title, @article.title %>
<%= stylesheet_link_tag 'wmd' %>
<%= stylesheet_link_tag 'token_input' %>

<% semantic_form_for @article do |form| %>	
<% form.buttons :class => "grid_8" do %>
	<li class="grid_4 alpha"><h1>Edit article</h1></li>
 	<li class="grid_4 omega" style="float:right;text-align:right;margin-right: -10px;"><%= link_to @article.published? ? "View on site" : "Preview on site", public_article_url(@article), :target => "_blank", :style=>"line-height: 1.2;" %>&nbsp;&nbsp;&nbsp;<%= form.submit "Save article" %></li>
<% end %>
	<div class="toolbox grid_4">
		<h4>Status</h4>
		<div>
			<% if @article.published? %>
				<p id="status" class="published">
					<span>Published</span> <strong><%= @article.published_at.to_s(:date) %></strong><br />
					<small>at <strong><%= @article.published_at.to_s(:time) %></strong>
					(<%= distance_of_time_in_words_to_now(@article.published_at) %> ago)</small>
				</p>
			<% elsif @article.scheduled? %>
				<p id="status" class="scheduled">
					<span>Scheduled</span> <strong><%= @article.published_at.to_s(:date) %></strong><br />
					<small>at <strong><%= @article.published_at.to_s(:time) %></strong>
					(<%= distance_of_time_in_words_to_now(@article.published_at) %> from now)</small>
				</p>
			<% elsif @article.awaiting_attention? %>	
				<% @article.sign_offs.last.tap do |last_sign_off| %>
					<p id="status" class="awaiting_attention">
							<span>Signed off</span> <small>by <strong><%= last_sign_off.user.name %></strong>,
							 	<%=last_sign_off.created_at.to_s(:date) %> at <%= last_sign_off.created_at.to_s(:time) %></small></p>
					</p>
					<% if @article.sign_offs.size > 1 %>
						<p><small>Also signed off:</small></p>
						<ul style="margin: 0 0 10px 0;">
							<% @article.sign_offs.all(:order => 'created_at desc').each do |sign_off| %>
								<% unless sign_off == last_sign_off %><li><small><strong style="font-weight: 600;"><%= sign_off.user.name %></strong> (<%=sign_off.created_at.to_s(:date) %> at <%= sign_off.created_at.to_s(:time) %>)</small></li><% end %>
							<% end %>
						</ul>
					<% end %>
				<% end %>
			<% else %>
				<p id="status" class="draft">
					<span>Draft</span>
				</p>
			<% end %>
			<div id="publish">
				<% if @article.status == "Published" -%>
					<%= form.submit "Unpublish", :class => "article_unpublish", :confirm => "Are you sure you want to unpublish this article?" %> <input type="button" value="Reschedule" class="show_schedule" />
				<% else -%>
					<%= form.submit "Publish", :class => "article_publish", :confirm => "Are you sure you want to publish this article?" %> <input type="button" value="Specify date" class="show_schedule" />
				<% end %>
				<% if @article.draft? || (@article.awaiting_attention? && !@article.signed_off_by?(current_user)) %>
					<%= form.submit "Sign off", :class=>"article_sign_off" %>
				<% elsif @article.awaiting_attention? && @article.signed_off_by?(current_user) %>
					<%= form.submit "Revoke sign off", :class=>"article_revoke_sign_off" %>
				<% end %>
			</div>
			<%= form.hidden_field :status %>
			<div id="schedule" style="display:none;">
				<label for="article[schedule][year]">Publish this article on:</label><br />
				<%= select_datetime (@article.published_at.nil? ? Time.now : @article.published_at), :order => [:month, :day, :year], :datetime_separator => "<br /> at ", :time_separator => ": ", :prefix => "article[schedule]" %>
				<%= form.submit "Schedule", :class => "article_publish" %>
			</div>
		</div>
		
		<% if @article.network_article? && @article.network_original.published? %>
			<div id="network_status">
				<p>This is a <u>network article</u>. It was originally published by <strong><%= @article.checkout.original_account.display_name %></strong>
				on <strong><%= @article.network_original.published_at.to_formatted_s(:standard) %></strong>.</p>
			</div>
		<% end %>
		
		<%= render :partial => 'printing' %>
	</div>
	
	<% form.inputs :class => "grid_8", :style => "clear:left;" do %>
		<%= form.input :title, :as => :string %>
		<%= form.input :subtitle, :as => :string %>
		<%= form.input :author_ids, :label => "Authors", :as => :string, :input_html => { :value => "" }, :wrapper_html => { :class => "grid_6 " } %>
		<%= form.input :section_id, :as => :select, :collection => @account.categories.sections.all, :label => "Section", :wrapper_html => { :class => "grid_2" } %>
		<%= form.input :summary, :as => :text, :input_html => { :rows => 2 }, :label => "Excerpt" %>
		<%= form.input :bodytext, :label => "Bodytext <a id=\"bodytext_preview_link\" href=\"#bodytext_preview\" style=\"float:right\">Preview formatting</a>".html_safe %>
	<% end %>
	
	<div class="toolbox grid_4">
		<h4>Categories</h4>
		<div id="document_categories">
			<% for category in @account.categories.sections.all %>
		  		<%= check_box_tag "article[category_ids][]", category.id, @article.categories.include?(category) %>
		  		<%= category.name %><br />
				<% unless category.subcategories.blank? %>
					<% category.subcategories.each do |subcategory| %>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= check_box_tag "article[category_ids][]", subcategory.id, @article.categories.include?(subcategory) %>
			  		<%= subcategory.name %><br />
						<% unless subcategory.subcategories.blank? %>
							<% subcategory.subcategories.each do |subsubsubcategory| %>
							&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= check_box_tag "article[category_ids][]", subsubsubcategory.id, @article.categories.include?(subsubsubcategory) %>
					  		<%= subsubsubcategory.name %><br />
							<% end %>
						<% end %>
					<% end %>
				<% end %>
			<% end %>
		</div>
	</div>
	
	<div class="toolbox grid_4">
		<h4>Media</h4>
		<div>
			<ol id="document_mediafiles">
				<%= render @article.waxings %>
			</ol>
			<a id="attach_mediafile_link" href="<%= new_document_mediafile_path(@article) %>" title="Attach media" class="link yellow">Attach media</a>
			<iframe name="upload_frame" style="display: none"></iframe>
		</div>
	</div>
	
	<div class="toolbox grid_4">
		<h4>Tags</h4>
		<div>
			<% form.inputs do %>
				<%= form.input :tag_list, :as => :text, :input_html => { :rows => 3 }, :wrapper_html => { :style => "margin-bottom: 0;width: 99%;" } %>
			<% end %>
		</div>
	</div>
	
	<div class="toolbox grid_4">
		<h4>Comments</h4>
		<div>
			<%= render :partial => 'comment_status' %>
			<% if @article.comments.blank? %>
				<span id="documents_comments_link" class="link inactive">No comments</span>
			<% else %>
				<a id="documents_comments_link" href="<%= article_comments_path(@article) %>" class="link yellow" >View <%= pluralize(@article.comments.count, 'comment')%></a>
			<% end %>
		</div>
	</div>
<% end %>

<div style="display: none;">
	<div id="bodytext_preview">
		<h1>Bodytext preview</h1>
		<div id="toggle_preview" class="state_control"><a href="#" class="formatted selected first">Formatted</a><a href="#" class="raw_html last">Raw HTML</a></div>
		<hr>
		<div id="wmd-preview">
		</div>
		<div id="wmd-output" style="display:none">
		</div>
	</div>
</div>

<% content_for :javascript do %>
	<%= javascript_include_tag 'jquery.tokeninput' %>
	<%= javascript_include_tag 'jquery.wmd' %>
	<script type="text/javascript">
		$().ready(function() {			
           	$("#article_bodytext").wmd({'preview':"wmd-preview"}); 

			$('#create_printing').live('click', function(event){
				$.ajax({ 
					'data': { 'printing[issue_id]' : $('#printing_issue_id').val() }, 
					'type' : 'POST', 
					'url' : '<%= article_printings_url(@article)%>',
					'beforeSend' : function(){ 
						$('#printings .spinner').show();
					} 
				});
				event.preventDefault();
			});
			
			$("a#documents_comments_link").fancybox({ 'centerOnScroll': true });
			
			$('#upload_media_form form').live('submit', function(){
				$.fancybox.showActivity();
			});
			
			
			$("#article_author_ids").tokenInput("<%= authors_path(:format => :json) %>", {
				initialValues: <%= @article.authors_json %>,
				canCreate: true,
				createText: "New author",
				hintText: "Add an author",
		        classes: {
		            tokenList: "token-input-list",
		            token: "token-input-token",
		            tokenDelete: "token-input-delete-token",
		            selectedToken: "token-input-selected-token",
		            highlightedToken: "token-input-highlighted-token",
		            dropdown: "token-input-dropdown",
		            dropdownItem: "token-input-dropdown-item",
		            dropdownItem2: "token-input-dropdown-item2",
		            selectedDropdownItem: "token-input-selected-dropdown-item",
		            inputToken: "token-input-input-token"
		        }
		   });	
		
			$(".edit_caption a").fancybox({
				'titlePosition'		: 'inside',
				'transitionIn'		: 'none',
				'transitionOut'		: 'none',
				'scrolling'			: 'no',
				'width'				: '500'
			});
        });
	</script>
<% end %>