config/routes.rb
ActionController::Routing::Routes.draw do |map|
  
  map.root :controller => :public_front_pages, :action => :show
  map.public_front_page '/', :controller => :public_front_pages, :action => :show

  map.public_article '/articles/:id', :controller => :public_articles, :action => :show
  map.public_page '/pages/*id', :controller => :public_pages, :action => :show
  map.public_category '/categories/*id', :controller => :public_categories, :action => :show
  map.public_search '/search', :controller => :public_search, :action => :show
  map.public_issues '/issues', :controller => :public_issues, :action => :index
  map.public_issue '/issues/:id', :controller => :public_issues, :action => :show
  map.public_blogs '/blogs', :controller => :public_blogs, :action => :index
  map.public_blog '/blogs/:id', :controller => :public_blogs, :action => :show
  map.public_blog_entry '/blogs/:blog_slug/:id', :controller => :public_entries, :action => :show
  map.public_comments '/comments', :controller => :public_comments, :action => :create, :conditions => { :method => :post }
  
  map.feed '/rss', :controller => :public_feeds, :action => :show
  map.feed '/feed.xml', :controller => :public_feeds, :action => :show

  map.front_page_preview '/front_page/preview', :controller => :public_front_pages, :action => :preview 
  
  # Admin routes
  map.admin '/admin', :controller => :dashboards, :action => :dashboard_redirect
  map.with_options(:path_prefix => "/admin") do |admin|
    admin.resources :password_resets
    admin.resources :account_invitations, :only => [:create, :edit, :update, :destroy]
    admin.resources :accounts
    admin.resources :articles, :collection => { :search => :get, :edit_multiple => :get, :update_multiple => :put }, :member => { :lock_comments => :put, :enable_comments => :put, :disable_comments => :put } do |article|
      article.comments '/comments', :controller => :articles, :action => :comments, :conditions => { :method => :get }
      article.resources :mediafiles
      article.resources :authors
      article.resources :tags
      article.resources :waxings
      article.resources :printings
    end
    admin.resources :authors
    admin.resources :blogs, :member => { :manage_contributors => :get, :add_contributor => :put, :remove_contributor => :put, :promote_contributor => :put, :demote_contributor => :put } do |blog|
      blog.resources :entries, :member => { :lock_comments => :put, :enable_comments => :put, :disable_comments => :put } do |entry|
        entry.comments '/comments', :controller => :entries, :action => :comments, :conditions => { :method => :get }
        entry.resources :mediafiles
        entry.resources :waxings
        entry.resources :tags
      end
    end
    admin.resources :categories, :member => { :deactivate => :put, :reactivate => :put }
    admin.resources :comments, :collection => { :search => :get }
    admin.current_design '/current_design', :controller => :designs, :action => :current_design
    admin.resource :dashboard
    admin.resources :designs do |design|
      design.resources :templates
      design.resources :template_files
    end
    admin.resources :documents do |document|
      document.resources :mediafiles
      document.resources :waxings
    end
    admin.resources :entries, :only => [:new, :edit, :update, :destroy], :collection => { :edit_multiple => :get, :update_multiple => :put } do |entry|
      entry.resources :mediafiles
      entry.resources :waxings
      entry.resources :tags
    end
    admin.resource :front_page, :only => [:edit, :update]
    admin.resources :issues, :member => { :upload_pdf => :post } 
    admin.resources :lists, :except => :show 
    admin.resources :mediafiles do |mediafile|
      mediafile.resources :authors
      mediafile.resources :tags
    end
    admin.resource :network, :member => { :checkout_article => :post, :search => :get } do |network|
      network.show_article '/articles/:id', :controller => :networks, :action => :show_article, :conditions => { :method => :get }
      network.show_members '/members', :controller => :networks, :action => :show_members, :conditions => { :method => :get }
      network.update_members '/members', :controller => :networks, :action => :update_members, :conditions => { :method => :post }
    end
    admin.resources :pages
    admin.resources :user_invitations, :only => [:create, :edit, :update, :destroy]
    admin.resources :users, :member => { :promote => :put, :demote => :put, :deputize => :put, :letgo => :delete }
    admin.resources :waxings
  end 
   
end

app/models/account.rb
class Account < ActiveRecord::Base
  include Pacecar
  
  # Main data models (and STI subclasses)
  has_many :mediafiles, :dependent => :destroy
  has_many :images
  has_many :audiofiles
  has_many :documents, :dependent => :destroy
  has_many :articles 
  has_many :entries
  has_many :authors, :dependent => :destroy
  has_many :categories, :order => "position", :conditions => { :active => true }, :dependent => :destroy
  has_many :sections, :order => "parent_id, position", :dependent => :destroy
  has_many :blogs, :dependent => :destroy
  has_many :issues, :dependent => :destroy, :order => "date desc"
  has_many :email_templates, :dependent => :destroy
  has_many :lists, :dependent => :destroy
  has_many :pages, :dependent => :destroy
  has_many :comments, :dependent  => :destroy
  has_many :user_invitations, :dependent => :destroy
  has_many :active_user_invitations, :class_name => 'UserInvitation', :conditions => { :redeemed => false }
  
  has_recent_records :articles
  named_scope :by_most_recently_published,lambda { {:joins => 'INNER JOIN documents ON documents.account_id=accounts.id', :group => 'accounts.id', :order => 'documents.updated_at', :conditions => ["documents.status = 'Published' AND documents.published_at <= ?", Time.now.utc]} }
  
  # Authentication
  has_many :users, :dependent => :destroy
  
  # Join models
  has_many :authorships, :dependent => :destroy
  has_many :photocredits, :dependent => :destroy
  has_many :printings, :dependent => :destroy
  has_many :sortings, :dependent => :destroy
  has_many :waxings, :dependent => :destroy
  
  # Special category functionality 
  has_many :main_categories, :class_name => "Category", :order => "position", :conditions => {:parent_id => nil } # An account's top-level categories
  accepts_nested_attributes_for :categories
  
  acts_as_authorizable
  acts_as_tagger

  validates_presence_of :time_zone, :message => "must indicate preferred time zone."
  
  validates_presence_of :name, :message => "Account must have a name"
  validates_uniqueness_of :name, :message => "Account name must be unique"
  validates_format_of :name, :with => /^[-a-z0-9]+$/
  
  serialize :settings
  serialize :lead_article_ids
  
  has_many  :designs
  belongs_to :current_design, :class_name => "Design", :foreign_key => :current_design_id
  
  # Settings defaults
  IMAGE_DEFAULT_SETTINGS = { 
            "thumb" => ['100>', 'jpg'],  
            "small" => ['250>', 'jpg'],
            "medium" => ['440>', 'jpg'],
            "large" => ['800>', 'jpg']
  }
  
  before_create :set_default_settings
    
  def settings
    read_attribute(:settings)
  end
  
  def display_name
    formal_name || name
  end
  
  FeedSettings = Struct.new("FeedSettings", :limit, :full_text)
  
  def feed_settings
    feed_settings = read_attribute(:settings)["feed"] || {}
    full_text = feed_settings["full_text"]=="true" ? true : false
    FeedSettings.new(feed_settings["limit"].to_i, full_text)
  end
  
  def feed_settings=(new_settings)
    account_settings = read_attribute(:settings)
    account_settings["feed"] = {} if settings["feed"].nil?
    account_settings["feed"].merge!(new_settings)
    write_attribute(:settings, account_settings)
  end
  
  def image_settings
    account_settings = read_attribute(:settings)
    account_settings["image"].nil? ? {} : account_settings["image"]
  end
  
  def image_settings=(new_settings)
    account_settings = read_attribute(:settings)
    account_settings["image"] = {} if settings["image"].nil?
    raise ArgumentError unless new_settings.is_a? Hash
    new_settings.each do |key, value|
      
      if value[:height].blank?
        new_height = ""
      else
        new_height="x" + value[:height]
      end
      
      if value[:width].blank?
        new_width = ""
      else
        new_width= value[:width]
      end
      
      account_settings["image"].update( key => [new_width + new_height + ">", "jpg"]) unless new_height.blank?&&new_width.blank?
    end
    write_attribute(:settings, account_settings)
  end
  
  # Human readable list of account managers
  def managers_list
    managers = self.has_managers
     case managers.length
     when 0
       return nil
     when 1
       return "#{managers.first.name} <#{managers.first.email}>"
     when 2
       return "#{managers.first.name} <#{managers.first.email}>" + " and " + "#{managers.second.name} <#{managers.second.email}>"
     else
      list = String.new
      (0..(managers.length - 3)).each{ |i| list += "#{managers[i].name} <#{managers[i].email}>, " }
      list += "#{managers[managers.length-2].name} <#{managers[managers.length-2].email}>" + " and " + "#{managers[managers.length-1].name} <#{managers[managers.length-1].email}>" # last two managers get special formatting
      return list
    end         
  end

  def to_xml(options = {})
     options[:indent] ||= 2
     xml = options[:builder] ||= Builder::XmlMarkup.new(:indent => options[:indent])
     xml.instruct! unless options[:skip_instruct]
     
     xml.account do
       xml.tag!( :id, self.id )       
       xml.tag!( :name, self.name)
       xml.tag!( :time_zone, self.time_zone)
     end
  end
  
  # Account user management
  def promote(user)
    if user.has_role?('staff', self)
      if user.has_role?('editor', self)
          user.has_no_role('editor', self)
          user.has_role('manager', self)
      else
        user.has_role('editor', self)
      end
    else
      user.has_role('staff', self)
    end
  end
  
  def demote(user)
    if user.has_role?('manager', self)
      user.has_no_role('manager', self)
      user.has_role('editor', self)
    elsif user.has_role?('editor', self)
      user.has_no_role('editor', self)
    elsif user.has_role?('staff', self)
      user.has_no_role('staff', self)
    end
  end
    
  # Network
  has_many :checkouts, :dependent => :destroy
  has_many :network_memberships, :class_name => "Membership", :foreign_key => :network_owner_id, :dependent => :destroy
  has_many :network_members, :through => :network_memberships, :source => :account
    
  def network_owner?
    !network_memberships.reload.empty?
  end
  
  def has_network_member?(potential_member)
    !!network_memberships.find_by_account_id(potential_member.id)
  end
  
  def network_member_ids
    network_memberships.collect{ |m| m.account_id }
  end
      
  def make_network_copy(article, user = nil)
    if has_network_member?(article.account)&&article.published?
      copy = article.clone
      copy.unpublish
      copy.update_attributes(:account => self, :section => nil)
    
      article.authors.each do |author|
        copy.authors << authors.find_or_create_by_name(author.name)
      end
      copy.tag_list = article.tag_list
      article.mediafiles.each do |m| 
        mediafile_copy = m.photocopy(self)
        copy.mediafiles << mediafile_copy 
        copy.waxing_for(mediafile_copy).update_attribute(:caption, article.waxing_for(m).caption)
      end
      checkouts.create(:original_article => article, :duplicate_article => copy, :user => user )
      copy
    end
  end  
  
  def has_network_copy_of?(article)
    !!find_network_copy_of(article)
  end
  
  def find_network_copy_of(article)
    checkout = checkouts.find_by_original_article_id(article.id)
    checkout.nil? ? nil : checkout.duplicate_article
  end
  
  def site_url
    read_attribute("site_url") || ""
  end
  
  private
  
  def set_default_settings
    write_attribute(:settings, { "image" => IMAGE_DEFAULT_SETTINGS } )
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  include Pacecar
  
  belongs_to :account

  has_many :authorships, :dependent => :destroy
  has_many :articles, :through => :authorships 
  
  has_many :photocredits, :dependent => :destroy
  has_many :mediafiles, :through => :photocredits
  
  validates_presence_of :account, :message => "must have an account"
  validates_associated :account, :message => "Account must be valid"
  validates_presence_of :name, :message => "must have a name"
  validates_uniqueness_of :name, :scope => :account_id
  
  def to_liquid
    { 'name' => name, 'id' => id }
  end
end

app/controllers/mediafiles_controller.rb
class MediafilesController < ApplicationController
  layout 'hotink'
  
  before_filter :find_article, :find_entry, :find_document
  
  # GET /mediafiles
  def index
    
    if params[:search].blank?
      @mediafiles = @account.mediafiles.paginate( :page=>(params[:page] || 1), :per_page => (params[:per_page] || 20 ), :order => "date DESC", :include => [:authors])
    else
      @search_query = params[:search]
      @mediafiles = @account.mediafiles.search(@search_query, :page=>(params[:page] || 1), :per_page => (params[:per_page] || 20 ), :order => :date, :sort_mode => :desc, :include => [:authors])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # GET /mediafiles/1
  def show
    @mediafile = @account.mediafiles.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /mediafiles/new
  def new
    @mediafile = @account.mediafiles.build
    if request.xhr?
      render :template => 'mediafiles/new.html.erb', :layout => false
    else
      render :action => :new
    end
  end

  # GET /mediafiles/1/edit
  def edit
    @mediafile = @account.mediafiles.find(params[:id])
     respond_to do |format|
       format.html # new.html.erb
     end
  end

  # POST /mediafiles
  def create
    if params[:mediafile][:file].respond_to?(:content_type)    
      # Catch various content types and build the appropriate media type
      case params[:mediafile][:file].content_type
      # Images
      when %r"jpe?g", %r"tiff?", %r"png", %r"gif", %r"bmp"    then @mediafile = @account.images.create(params[:mediafile].merge(:settings => @account.settings["image"]))
      # mp3s/Audiofiles
      when  %r"audio\/mpeg", %r"audio\/mpg"                   then @mediafile = @account.audiofiles.create(params[:mediafile])
      # Catch-all for generic file attachments
      else @mediafile = @account.mediafiles.create(params[:mediafile])
      end    

      respond_to do |format|
        flash[:notice] = 'Media added'
            #Special behaviour to mimic ajax file-upload on article & entry form, if it's an iframe
            if params[:iframe_post] && @document
              @article = @document # articles/article_mediafile partial expects @article
              @waxing = @account.waxings.create(:document_id => @document.id, :mediafile_id=> @mediafile.id);
              responds_to_parent do
                render :update do |page|
                  page << "$.fancybox.close();
                           $('#document_mediafiles').html('#{ escape_javascript render(@document.waxings) } '); 
                           $('.edit_caption a').fancybox({
                             'scrolling'			: 'no',
                             'titlePosition'		: 'inside',
                             'transitionIn'		: 'none',
                             'transitionOut'		: 'none',
                             'width'				: '500'
                           });"
          			end
              end
              return
            end
        format.html { redirect_to(edit_mediafile_path(@mediafile)) }
      end  
     else
       render :text => "Mediafile NOT uploaded", :status => :bad_request
    end
  rescue NoMethodError # Raised in the case that there's no file supplied (on line 54 `params[:mediafile]` will be nil, hence `params[:mediafile][:file]` raises error)
   if @document 
      @article = @document # articles/article_mediafile partial expects @article
      responds_to_parent do
  			render :update do |page|
  				page << "$.fancybox.close();$('#document_mediafiles').html('#{ escape_javascript render(@document.waxings) }')"
  			end
      end
    else
      flash[:notice] = "No mediafile uploaded"
      redirect_to new_mediafile_url
    end
  end

  # PUT /mediafiles/1
  def update
    @mediafile = @account.mediafiles.find(params[:id])
   	#@mediafile.date = params[@mediafile.class.name.underscore.to_sym][:date]
   	#params.delete(:date)
    respond_to do |format|
      if @mediafile.update_attributes(params[@mediafile.class.name.downcase.to_sym]) 
        flash[:notice] = 'Media updated'      
        format.html { redirect_to(mediafiles_path)}
      else
        flash[:notice] = 'Error! Media NOT updated'      
        format.html { render :action => "edit", :status => :bad_request }
      end
    end
  end

  # DELETE /mediafiles/1
  # DELETE /mediafiles/1.xml
  def destroy
    @mediafile = @account.mediafiles.find(params[:id])
    @mediafile.destroy

    respond_to do |format|
      flash[:notice] = 'Media trashed'
      format.html { redirect_to(mediafiles_path) }
      format.js   { head :ok }
    end
  end
end

app/helpers/mediafiles_helper.rb
module MediafilesHelper
  
  def title_for(mediafile)
    if mediafile.title.blank?
      if mediafile.is_a? Audiofile
        if mediafile.song_title.blank?
          mediafile.file_file_name
        else
          if mediafile.artist.blank?
            mediafile.song_title
          else
            mediafile.song_title + " - " + mediafile.artist
          end
        end
      else
        mediafile.file_file_name
      end
    else
      mediafile.title
    end
  end
  
end

app/views/mediafiles/_ajax_pagination.html.erb
<%= will_paginate(@mediafiles, :inner_window => 1, :outer_window => 1, :class => "pagination remote" ) %>

app/views/mediafiles/_attach_media.html.erb
<div class="small_top_button clearfix"><a href="#" class="close_window" onclick="page_overlay.end();return false;"> <img src="/images/window_x.png" /> </a></div>
<div id="upload_media_container" class="column_holder clearfix">
	<div class="title_bar clearfix">
		<div class="actions">	
			<h1>Attach media </h1>
			<%= button_link_to_remote 'Attach archive media &raquo;', :url=>new_account_document_waxing_url(@account, @document, :format=>:js), :method => :get, :html=>{ :class=>'primary', :style => "float: right;" } %>
		</div>
	</div>
	<div id="upload_media_form" class="two_thirds_column">
				<h4>Upload media file</h4>
			<div>
					<% form_tag account_document_mediafiles_url(@account, @document), :method => :post, :multipart=>true, :target=>"upload_frame", :onsubmit => "page_overlay.end();$('mediafiles_list').insert('<img class=\"mediafile_loading\" style=\"margin: 1em 1.5em;\" src=\"/loading.gif\" />');" do %>
						<p>
							<%= label_tag 'mediafile[file]', "Media file" %><br />
							<%= file_field_tag 'mediafile[file]', :class=>"text_input" %>			
						</p>
						<p style="text-align:left;padding-top:10px;">
							<%= button_link_to_submit "Upload", :class=>"large save" %>
						</p>
						<%= hidden_field_tag 'iframe_post', true %>
					<% end %>
			</div>
	</div>
	<div class="third_column">
			<p class="faq question">What types of file can I upload?</p>
			<p class="faq answer">You can upload any type of file you want, but the system offers special support for a 
				few file types. They are:</p>
				<dl class="faq">
					<dt>jpeg, jpg, png, gif, tiff, or bmp</dt>
					<dd>Images will be displayed alongside your article.</dd>
					<dt>mp3</dt>
					<dd>Audio is playable in the browser window.</dd>
				</dl>
			<p class="faq answer">Other files can also be uploaded, attached and captioned alongside articles, but with no 
				special consideration.</p>
		</div>
</div>
<script type="text/javascript" charset="utf-8">
	load_button_fix();
</script>

app/views/mediafiles/_audiofile.html.erb
<div class="audiofile">
	<object type="application/x-shockwave-flash" data="/player_mp3.swf" style="margin-bottom:10px;" width="360" height="20">
	    <param name="movie" value="/player_mp3.swf" />
	    <param name="bgcolor" value="#ffffff" />
	    <param name="FlashVars" value="mp3=<%= audiofile.file.url %>&width=360" />
	</object>
	<small><%= audiofile.filename %> - <%= number_to_human_size(audiofile.file_size) %> - <%= link_to "Download", audiofile.url(:original, false) %></small>
	
	<ul class="mp3_info">
		<% unless audiofile.artist.blank? %><li><strong>Artist</strong>&nbsp;&nbsp;<%= audiofile.artist %></li><% end %>
		<% unless audiofile.song_title.blank? %><li><strong>Song title </strong>&nbsp;&nbsp;<%= audiofile.song_title %></li><% end %>
		<% unless audiofile.album.blank? %><li><strong>Album </strong>&nbsp;&nbsp;<%= audiofile.album %></li><% end %>
		<% unless audiofile.release_year.blank? %><li><strong>Year </strong>&nbsp;&nbsp;<%= audiofile.release_year %></li><% end %>
		<% unless audiofile.length.blank? %><li><strong>Length </strong>&nbsp;&nbsp;<%= audiofile.length / 60 %>:<%= (audiofile.length % 60)<10 ? "0#{audiofile.length % 60}" : audiofile.length % 60 %></li><% end %>
		<li><strong>Url </strong>&nbsp;&nbsp;<small><input value="<%= audiofile.url(:original, false) %>" size="40"/></small></li>
	</ul>
</div>

app/views/mediafiles/_file.html.erb
<div class="file">
	<%= image_tag "blank_file_icon.png", :style => "float:left; border:none; margin-right: 5px; " %> <%= file.filename %> 
	<span style="font-size: 0.75em;"><%= number_to_human_size(file.file_size) %></span>
	- 
	<span style="font-size: 0.75em;"><%= link_to "Download", file.url(:original, false) %></span>
</div>

app/views/mediafiles/_mediafile.html.erb
<li id="mediafile_<%= mediafile.id %>" class="<%= cycle("even-row", "odd-row") %> clearfix">
	<div class="clearfix">
		<div class="select">
			<input type="checkbox" value="<%= mediafile.id %>" name="mediafile_ids[]"/>
		</div>
	
			<% if mediafile.is_a?(Image) %>
		<div class="file">
				<%= image_tag(mediafile.file.url(:system_thumb)) %>
			<% elsif mediafile.is_a?(Audiofile) %>
		<div class="file blank_file">
				<p><%= mediafile.file_file_name.split(".").last.upcase %></p>
			<% else %>
		<div class="file blank_file">
				<p><%= mediafile.file_file_name.split(".").last.upcase %></p>			
			<% end %>
		</div>
	
		<div class="details">
			<h1><%=link_to h(title_for(mediafile)), edit_mediafile_url(mediafile), :class=>"document_link" %></h1>
			<p><%= mediafile.authors_list %></p>
		</div>
	
		<div class="tags">
			<% unless mediafile.tag_list.blank? %>
				<p><em> <%= mediafile.tag_list %></em></p>
			<% else %>
				<p><em> <span style="color: #BBB">No tags</span> </em></p>
			<% end %>
		</div>
	
		<div class="date">
			<p><%= h mediafile.date.to_time.to_s(:date) %></p>
		</div>

		<%= link_to "x", mediafile_path(mediafile), :confirm => "You are about to delete the mediafile: \n \n &quot;" + h(mediafile.title) + "&quot;\n \n Click 'OK' to delete or 'Cancel' to return to the page.", :method => :delete, :class=>"destroy_link" %>
	</div>
</li>

app/views/mediafiles/_pagination.html.erb
<%= will_paginate(@mediafiles, :inner_window => 1, :outer_window => 1) %>
<div id="mediafiles_page_info" class="page_entries_info">
	<%= page_entries_info @mediafiles %>
</div>

app/views/mediafiles/edit.html.erb
<p><%= link_to("&laquo Back", mediafiles_url )%></p>

<%= stylesheet_link_tag 'wmd' %>
<%= stylesheet_link_tag 'token_input' %>

<% semantic_form_for @mediafile, :url => mediafile_path(@mediafile) do |form| %>	
<div class="toolbox mediafile_file grid_6">
	<h4>Media</h4>
	<% if @mediafile.is_a? Image %>
		<%= render :partial => "image", :object => @mediafile %>
	<% elsif @mediafile.is_a? Audiofile %>
		<%= render :partial => "audiofile", :object => @mediafile %>
	<% else %>
		<%= render :partial => "file", :object => @mediafile %>
	<% end %>
</div>


<% form.buttons :class => "grid_6" do %>
	<li class="grid_4 alpha"><h1>Edit <%= @mediafile.class.name.humanize.downcase %></h1></li>
 	<li class="grid_2 omega" style="float:right;text-align:right;margin-right: -10px;"><%= form.submit "Save" %></li>
<% end %>

<% form.inputs :class => "grid_6", :style => "clear:left;" do %>
	<%= form.input :title, :as => :string %>
	<%= form.input :author_ids, :label => "Authors", :as => :string, :input_html => { :value => "" } %>
	<%= form.input :tag_list, :as => :string %>
	<%= form.input :description, :input_html => { :rows => 20 } %>
<% end %>

<% end %>
<% content_for :javascript do %>
	<%= javascript_include_tag 'jquery.tokeninput' %>
	<%= javascript_include_tag 'jquery.wmd' %>
	<script type="text/javascript">
		$().ready(function() {			
           	$("#image_description, #audiofile_description, #mediafile_description").wmd({"preview":false}); 

			$('#show_image_sizes_link').click(function(event){
				$('.image .sizes').slideToggle('slow', function(){
					if($('#show_image_sizes_link').html()=="Show sizes") {
						$('#show_image_sizes_link').html("Hide sizes")	
					} else {
						$('#show_image_sizes_link').html("Show sizes")	
					}
				});
				event.preventDefault();
			});

			$("#image_author_ids, #audiofile_author_ids, #mediafile_author_ids").tokenInput("<%= authors_path(:format => :json) %>", {
				initialValues: <%= @mediafile.authors_json %>,
				canCreate: true,
				createText: "New author",
				hintText: "Add an author",
		        classes: {
		            tokenList: "token-input-list",
		            token: "token-input-token",
		            tokenDelete: "token-input-delete-token",
		            selectedToken: "token-input-selected-token",
		            highlightedToken: "token-input-highlighted-token",
		            dropdown: "token-input-dropdown",
		            dropdownItem: "token-input-dropdown-item",
		            dropdownItem2: "token-input-dropdown-item2",
		            selectedDropdownItem: "token-input-selected-dropdown-item",
		            inputToken: "token-input-input-token"
		        }
		   });	

		});
	</script>
<% end %>

app/views/mediafiles/show.html.erb
<p>
  <b>Filename:</b>
  <%=h @attachment.filename %>
</p>

<p>
  <b>File type:</b>
  <%=h @attachment.file_type %>
</p>

<p>
  <b>Filesize:</b>
  <%=h @attachment.filesize %>
</p>

<p>
  <b>Title:</b>
  <%=h @attachment.title %>
</p>

<p>
  <b>Description:</b>
  <%=h @attachment.description %>
</p>

<p>
  <b>Width:</b>
  <%=h @attachment.width %>
</p>

<p>
  <b>Height:</b>
  <%=h @attachment.height %>
</p>

<p>
  <b>Length:</b>
  <%=h @attachment.length %>
</p>

<p>
  <b>Link alternate:</b>
  <%=h @attachment.link_alternate %>
</p>

<p>
  <b>Date:</b>
  <%=h @attachment.date %>
</p>

<p>
  <b>Account:</b>
  <%=h @attachment.account_id %>
</p>

<p>
  <b>Type:</b>
  <%=h @attachment.type %>
</p>


<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>